name: Build 3W6 llpamies Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup and Build
        run: |
          export QMK_HOME='~/work/qmk_firmware/qmk_firmware'
          pip install milc
          find ~/work/
          ~/work/qmk_firmware/qmk_firmware/util/qmk_install.sh
          python3 -m pip install --user qmk
          qmk setup -y
          qmk compile -kb 3w6/rev2 -km llpamies

      - name: Upload compiled firmware (build artifact)
        uses: actions/upload-artifact@v2
        with:
          name: 3W6_llpamies_firmware
          path: ~/qmk_firmware/3w6_rev2_llpamies.hex
